params:
  seed: 0

  algo:
    name: sac

  model:
    name: soft_actor_critic

  network:
    name: soft_actor_critic
    separate: True
    space:
      continuous:
    mlp:
      units: [256, 128, 64]
      activation: relu
      d2rl: False
      initializer:
        name: default
    log_std_bounds: [-5, 2]

  config:
    name: default
    full_experiment_name: default
    env_name: rlgpu
    device: cuda:0
    device_name: cuda:0
    normalize_input: True
    reward_shaper:
      scale_value: 0.1

    gamma: 0.99
    lr_schedule: linear
    mini_epochs: 5

    max_epochs: 1000
    num_actors: 2048
    num_steps_per_episode: 200
    max_env_steps: 500
    batch_size: 1024
    replay_buffer_size: 2000000

    init_alpha: 0.2
    learnable_temperature: True
    target_entropy_coef: 0.5
    actor_lr: 3.0e-4
    critic_lr: 3.0e-4
    alpha_lr: 3.0e-4
    critic_tau: 0.005
    actor_update_interval: 1
    target_update_interval: 1

    num_warmup_steps: 100000
    warmup_mode: steps
    updates_per_step: 4

    min_alpha: 1.0e-4
    log_alpha_min: -16.0
    log_alpha_max: 2.0
    grad_norm: 0.0

    save_best_after: 20
    score_to_win: 20000
    save_frequency: 50
    print_stats: True

    player:
      games_num: 1
      max_games_per_worker: 1
      deterministic: True
